/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campominado;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jpescola
 */
public class CampoMinado extends javax.swing.JFrame {

    private final JLabel[] botoes;
    private int[] itens;
    private boolean novoJogo;
    private final int qtd_minas = 15; // qtd minas no tabuleiro

    private final Color CASA_CLARA = new Color(170, 215, 81);
    private final Color CASA_ESCURA = new Color(162, 209, 73);
    private final Color CASA_CLARA_USADA = new Color(229, 194, 159);
    private final Color CASA_ESCURA_USADA = new Color(215, 184, 153);
    private final Color COR_NUMERO_UM = new Color(25, 118, 210);
    private final Color COR_NUMERO_DOIS = new Color(56, 142, 60);
    private final Color COR_NUMERO_TRES = new Color(211, 47, 47);
    private final Color COR_NUMERO_QUATRO = new Color(123, 31, 162);
    private final Color COR_NUMERO_CINCO = new Color(255, 143, 0);

    /**
     * Creates new form CampoMinado
     */
    public CampoMinado() {
        initComponents();
        botoes = new JLabel[]{b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b30, b31, b32, b33, b34, b35, b36, b37, b38, b39, b40, b41, b42, b43, b44, b45, b46, b47, b48, b49, b50, b51, b52, b53, b54, b55, b56, b57, b58, b59, b60, b61, b62, b63};
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b0 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        b16 = new javax.swing.JLabel();
        b17 = new javax.swing.JLabel();
        b18 = new javax.swing.JLabel();
        b19 = new javax.swing.JLabel();
        b20 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        b23 = new javax.swing.JLabel();
        b24 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        b26 = new javax.swing.JLabel();
        b27 = new javax.swing.JLabel();
        b28 = new javax.swing.JLabel();
        b29 = new javax.swing.JLabel();
        b30 = new javax.swing.JLabel();
        b31 = new javax.swing.JLabel();
        b32 = new javax.swing.JLabel();
        b33 = new javax.swing.JLabel();
        b34 = new javax.swing.JLabel();
        b35 = new javax.swing.JLabel();
        b36 = new javax.swing.JLabel();
        b37 = new javax.swing.JLabel();
        b38 = new javax.swing.JLabel();
        b39 = new javax.swing.JLabel();
        b40 = new javax.swing.JLabel();
        b41 = new javax.swing.JLabel();
        b42 = new javax.swing.JLabel();
        b43 = new javax.swing.JLabel();
        b44 = new javax.swing.JLabel();
        b45 = new javax.swing.JLabel();
        b46 = new javax.swing.JLabel();
        b47 = new javax.swing.JLabel();
        b48 = new javax.swing.JLabel();
        b49 = new javax.swing.JLabel();
        b50 = new javax.swing.JLabel();
        b51 = new javax.swing.JLabel();
        b52 = new javax.swing.JLabel();
        b53 = new javax.swing.JLabel();
        b54 = new javax.swing.JLabel();
        b55 = new javax.swing.JLabel();
        b56 = new javax.swing.JLabel();
        b57 = new javax.swing.JLabel();
        b58 = new javax.swing.JLabel();
        b59 = new javax.swing.JLabel();
        b60 = new javax.swing.JLabel();
        b61 = new javax.swing.JLabel();
        b62 = new javax.swing.JLabel();
        b63 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado");
        setBackground(new java.awt.Color(0, 255, 0));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridLayout(8, 8));

        b0.setBackground(new java.awt.Color(227, 255, 0));
        b0.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 0, 0));
        b0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b0.setText("1");
        b0.setOpaque(true);
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b0);

        b1.setBackground(new java.awt.Color(0, 255, 0));
        b1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 0));
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setText("1");
        b1.setOpaque(true);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b1);

        b2.setBackground(new java.awt.Color(227, 255, 0));
        b2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 0, 0));
        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setText("1");
        b2.setOpaque(true);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b2);

        b3.setBackground(new java.awt.Color(0, 255, 0));
        b3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 0, 0));
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setText("1");
        b3.setOpaque(true);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b3);

        b4.setBackground(new java.awt.Color(227, 255, 0));
        b4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 0, 0));
        b4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4.setText("1");
        b4.setOpaque(true);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b4);

        b5.setBackground(new java.awt.Color(0, 255, 0));
        b5.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 0, 0));
        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setText("1");
        b5.setOpaque(true);
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b5);

        b6.setBackground(new java.awt.Color(227, 255, 0));
        b6.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 0, 0));
        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setText("1");
        b6.setOpaque(true);
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b6);

        b7.setBackground(new java.awt.Color(0, 255, 0));
        b7.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 0, 0));
        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setText("1");
        b7.setOpaque(true);
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b7);

        b8.setBackground(new java.awt.Color(0, 255, 0));
        b8.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 0, 0));
        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setText("1");
        b8.setOpaque(true);
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b8);

        b9.setBackground(new java.awt.Color(227, 255, 0));
        b9.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 0, 0));
        b9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b9.setText("1");
        b9.setOpaque(true);
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b9);

        b10.setBackground(new java.awt.Color(0, 255, 0));
        b10.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b10.setForeground(new java.awt.Color(255, 0, 0));
        b10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b10.setText("1");
        b10.setOpaque(true);
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b10);

        b11.setBackground(new java.awt.Color(227, 255, 0));
        b11.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b11.setForeground(new java.awt.Color(255, 0, 0));
        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setText("1");
        b11.setOpaque(true);
        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b11);

        b12.setBackground(new java.awt.Color(0, 255, 0));
        b12.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b12.setForeground(new java.awt.Color(255, 0, 0));
        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setText("1");
        b12.setOpaque(true);
        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b12);

        b13.setBackground(new java.awt.Color(227, 255, 0));
        b13.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b13.setForeground(new java.awt.Color(255, 0, 0));
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.setText("1");
        b13.setOpaque(true);
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b13);

        b14.setBackground(new java.awt.Color(0, 255, 0));
        b14.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b14.setForeground(new java.awt.Color(255, 0, 0));
        b14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b14.setText("1");
        b14.setOpaque(true);
        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b14);

        b15.setBackground(new java.awt.Color(227, 255, 0));
        b15.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b15.setForeground(new java.awt.Color(255, 0, 0));
        b15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b15.setText("1");
        b15.setOpaque(true);
        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b15);

        b16.setBackground(new java.awt.Color(227, 255, 0));
        b16.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b16.setForeground(new java.awt.Color(255, 0, 0));
        b16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b16.setText("1");
        b16.setOpaque(true);
        b16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b16);

        b17.setBackground(new java.awt.Color(0, 255, 0));
        b17.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b17.setForeground(new java.awt.Color(255, 0, 0));
        b17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b17.setText("1");
        b17.setOpaque(true);
        b17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b17);

        b18.setBackground(new java.awt.Color(227, 255, 0));
        b18.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b18.setForeground(new java.awt.Color(255, 0, 0));
        b18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b18.setText("1");
        b18.setOpaque(true);
        b18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b18);

        b19.setBackground(new java.awt.Color(0, 255, 0));
        b19.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b19.setForeground(new java.awt.Color(255, 0, 0));
        b19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b19.setText("1");
        b19.setOpaque(true);
        b19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b19);

        b20.setBackground(new java.awt.Color(227, 255, 0));
        b20.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b20.setForeground(new java.awt.Color(255, 0, 0));
        b20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b20.setText("1");
        b20.setOpaque(true);
        b20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b20);

        b21.setBackground(new java.awt.Color(0, 255, 0));
        b21.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b21.setForeground(new java.awt.Color(255, 0, 0));
        b21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b21.setText("1");
        b21.setOpaque(true);
        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b21);

        b22.setBackground(new java.awt.Color(227, 255, 0));
        b22.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b22.setForeground(new java.awt.Color(255, 0, 0));
        b22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b22.setText("1");
        b22.setOpaque(true);
        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b22);

        b23.setBackground(new java.awt.Color(0, 255, 0));
        b23.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b23.setForeground(new java.awt.Color(255, 0, 0));
        b23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b23.setText("1");
        b23.setOpaque(true);
        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b23);

        b24.setBackground(new java.awt.Color(0, 255, 0));
        b24.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b24.setForeground(new java.awt.Color(255, 0, 0));
        b24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b24.setText("1");
        b24.setOpaque(true);
        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b24);

        b25.setBackground(new java.awt.Color(227, 255, 0));
        b25.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b25.setForeground(new java.awt.Color(255, 0, 0));
        b25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b25.setText("1");
        b25.setOpaque(true);
        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b25);

        b26.setBackground(new java.awt.Color(0, 255, 0));
        b26.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b26.setForeground(new java.awt.Color(255, 0, 0));
        b26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b26.setText("1");
        b26.setOpaque(true);
        b26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b26);

        b27.setBackground(new java.awt.Color(227, 255, 0));
        b27.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b27.setForeground(new java.awt.Color(255, 0, 0));
        b27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b27.setText("1");
        b27.setOpaque(true);
        b27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b27);

        b28.setBackground(new java.awt.Color(0, 255, 0));
        b28.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b28.setForeground(new java.awt.Color(255, 0, 0));
        b28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b28.setText("1");
        b28.setOpaque(true);
        b28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b28);

        b29.setBackground(new java.awt.Color(227, 255, 0));
        b29.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b29.setForeground(new java.awt.Color(255, 0, 0));
        b29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b29.setText("1");
        b29.setOpaque(true);
        b29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b29);

        b30.setBackground(new java.awt.Color(0, 255, 0));
        b30.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b30.setForeground(new java.awt.Color(255, 0, 0));
        b30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b30.setText("1");
        b30.setOpaque(true);
        b30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b30);

        b31.setBackground(new java.awt.Color(227, 255, 0));
        b31.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b31.setForeground(new java.awt.Color(255, 0, 0));
        b31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b31.setText("1");
        b31.setOpaque(true);
        b31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b31);

        b32.setBackground(new java.awt.Color(227, 255, 0));
        b32.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b32.setForeground(new java.awt.Color(255, 0, 0));
        b32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b32.setText("1");
        b32.setOpaque(true);
        b32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b32);

        b33.setBackground(new java.awt.Color(0, 255, 0));
        b33.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b33.setForeground(new java.awt.Color(255, 0, 0));
        b33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b33.setText("1");
        b33.setOpaque(true);
        b33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b33);

        b34.setBackground(new java.awt.Color(227, 255, 0));
        b34.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b34.setForeground(new java.awt.Color(255, 0, 0));
        b34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b34.setText("1");
        b34.setOpaque(true);
        b34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b34);

        b35.setBackground(new java.awt.Color(0, 255, 0));
        b35.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b35.setForeground(new java.awt.Color(255, 0, 0));
        b35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b35.setText("1");
        b35.setOpaque(true);
        b35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b35);

        b36.setBackground(new java.awt.Color(227, 255, 0));
        b36.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b36.setForeground(new java.awt.Color(255, 0, 0));
        b36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b36.setText("1");
        b36.setOpaque(true);
        b36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b36);

        b37.setBackground(new java.awt.Color(0, 255, 0));
        b37.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b37.setForeground(new java.awt.Color(255, 0, 0));
        b37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b37.setText("1");
        b37.setOpaque(true);
        b37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b37);

        b38.setBackground(new java.awt.Color(227, 255, 0));
        b38.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b38.setForeground(new java.awt.Color(255, 0, 0));
        b38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b38.setText("1");
        b38.setOpaque(true);
        b38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b38);

        b39.setBackground(new java.awt.Color(0, 255, 0));
        b39.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b39.setForeground(new java.awt.Color(255, 0, 0));
        b39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b39.setText("1");
        b39.setOpaque(true);
        b39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b39);

        b40.setBackground(new java.awt.Color(0, 255, 0));
        b40.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b40.setForeground(new java.awt.Color(255, 0, 0));
        b40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b40.setText("1");
        b40.setOpaque(true);
        b40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b40);

        b41.setBackground(new java.awt.Color(227, 255, 0));
        b41.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b41.setForeground(new java.awt.Color(255, 0, 0));
        b41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b41.setText("1");
        b41.setOpaque(true);
        b41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b41);

        b42.setBackground(new java.awt.Color(0, 255, 0));
        b42.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b42.setForeground(new java.awt.Color(255, 0, 0));
        b42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b42.setText("1");
        b42.setOpaque(true);
        b42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b42);

        b43.setBackground(new java.awt.Color(227, 255, 0));
        b43.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b43.setForeground(new java.awt.Color(255, 0, 0));
        b43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b43.setText("1");
        b43.setOpaque(true);
        b43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b43);

        b44.setBackground(new java.awt.Color(0, 255, 0));
        b44.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b44.setForeground(new java.awt.Color(255, 0, 0));
        b44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b44.setText("1");
        b44.setOpaque(true);
        b44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b44);

        b45.setBackground(new java.awt.Color(227, 255, 0));
        b45.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b45.setForeground(new java.awt.Color(255, 0, 0));
        b45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b45.setText("1");
        b45.setOpaque(true);
        b45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b45);

        b46.setBackground(new java.awt.Color(0, 255, 0));
        b46.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b46.setForeground(new java.awt.Color(255, 0, 0));
        b46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b46.setText("1");
        b46.setOpaque(true);
        b46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b46);

        b47.setBackground(new java.awt.Color(227, 255, 0));
        b47.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b47.setForeground(new java.awt.Color(255, 0, 0));
        b47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b47.setText("1");
        b47.setOpaque(true);
        b47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b47);

        b48.setBackground(new java.awt.Color(227, 255, 0));
        b48.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b48.setForeground(new java.awt.Color(255, 0, 0));
        b48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b48.setText("1");
        b48.setOpaque(true);
        b48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b48);

        b49.setBackground(new java.awt.Color(0, 255, 0));
        b49.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b49.setForeground(new java.awt.Color(255, 0, 0));
        b49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b49.setText("1");
        b49.setOpaque(true);
        b49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b49);

        b50.setBackground(new java.awt.Color(227, 255, 0));
        b50.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b50.setForeground(new java.awt.Color(255, 0, 0));
        b50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b50.setText("1");
        b50.setOpaque(true);
        b50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b50);

        b51.setBackground(new java.awt.Color(0, 255, 0));
        b51.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b51.setForeground(new java.awt.Color(255, 0, 0));
        b51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b51.setText("1");
        b51.setOpaque(true);
        b51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b51);

        b52.setBackground(new java.awt.Color(227, 255, 0));
        b52.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b52.setForeground(new java.awt.Color(255, 0, 0));
        b52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b52.setText("1");
        b52.setOpaque(true);
        b52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b52);

        b53.setBackground(new java.awt.Color(0, 255, 0));
        b53.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b53.setForeground(new java.awt.Color(255, 0, 0));
        b53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b53.setText("1");
        b53.setOpaque(true);
        b53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b53);

        b54.setBackground(new java.awt.Color(227, 255, 0));
        b54.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b54.setForeground(new java.awt.Color(255, 0, 0));
        b54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b54.setText("1");
        b54.setOpaque(true);
        b54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b54);

        b55.setBackground(new java.awt.Color(0, 255, 0));
        b55.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b55.setForeground(new java.awt.Color(255, 0, 0));
        b55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b55.setText("1");
        b55.setOpaque(true);
        b55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b55);

        b56.setBackground(new java.awt.Color(0, 255, 0));
        b56.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b56.setForeground(new java.awt.Color(255, 0, 0));
        b56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b56.setText("1");
        b56.setOpaque(true);
        b56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b56);

        b57.setBackground(new java.awt.Color(227, 255, 0));
        b57.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b57.setForeground(new java.awt.Color(255, 0, 0));
        b57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b57.setText("1");
        b57.setOpaque(true);
        b57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b57);

        b58.setBackground(new java.awt.Color(0, 255, 0));
        b58.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b58.setForeground(new java.awt.Color(255, 0, 0));
        b58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b58.setText("1");
        b58.setOpaque(true);
        b58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b58);

        b59.setBackground(new java.awt.Color(227, 255, 0));
        b59.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b59.setForeground(new java.awt.Color(255, 0, 0));
        b59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b59.setText("1");
        b59.setOpaque(true);
        b59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b59);

        b60.setBackground(new java.awt.Color(0, 255, 0));
        b60.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b60.setForeground(new java.awt.Color(255, 0, 0));
        b60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b60.setText("1");
        b60.setOpaque(true);
        b60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b60);

        b61.setBackground(new java.awt.Color(227, 255, 0));
        b61.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b61.setForeground(new java.awt.Color(255, 0, 0));
        b61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b61.setText("1");
        b61.setOpaque(true);
        b61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b61);

        b62.setBackground(new java.awt.Color(0, 255, 0));
        b62.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b62.setForeground(new java.awt.Color(255, 0, 0));
        b62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b62.setText("1");
        b62.setOpaque(true);
        b62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b62);

        b63.setBackground(new java.awt.Color(227, 255, 0));
        b63.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        b63.setForeground(new java.awt.Color(255, 0, 0));
        b63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b63.setText("1");
        b63.setOpaque(true);
        b63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoMinado.this.mouseClicked(evt);
            }
        });
        getContentPane().add(b63);

        jMenuBar1.setBackground(new java.awt.Color(0, 255, 0));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Jogo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        limpar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        jogar(evt);
    }//GEN-LAST:event_mouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampoMinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampoMinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampoMinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampoMinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampoMinado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b0;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b17;
    private javax.swing.JLabel b18;
    private javax.swing.JLabel b19;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b20;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b26;
    private javax.swing.JLabel b27;
    private javax.swing.JLabel b28;
    private javax.swing.JLabel b29;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b30;
    private javax.swing.JLabel b31;
    private javax.swing.JLabel b32;
    private javax.swing.JLabel b33;
    private javax.swing.JLabel b34;
    private javax.swing.JLabel b35;
    private javax.swing.JLabel b36;
    private javax.swing.JLabel b37;
    private javax.swing.JLabel b38;
    private javax.swing.JLabel b39;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b40;
    private javax.swing.JLabel b41;
    private javax.swing.JLabel b42;
    private javax.swing.JLabel b43;
    private javax.swing.JLabel b44;
    private javax.swing.JLabel b45;
    private javax.swing.JLabel b46;
    private javax.swing.JLabel b47;
    private javax.swing.JLabel b48;
    private javax.swing.JLabel b49;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b50;
    private javax.swing.JLabel b51;
    private javax.swing.JLabel b52;
    private javax.swing.JLabel b53;
    private javax.swing.JLabel b54;
    private javax.swing.JLabel b55;
    private javax.swing.JLabel b56;
    private javax.swing.JLabel b57;
    private javax.swing.JLabel b58;
    private javax.swing.JLabel b59;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b60;
    private javax.swing.JLabel b61;
    private javax.swing.JLabel b62;
    private javax.swing.JLabel b63;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    // limpa o tabuleiro para novo jogo
    private void limpar() {
        novoJogo = true;
        int n = 0; // controla o nome
        int i = 0; // contagem para alternar cores das casas
        int p = 0; // controla as linhas (par ou ímpar)
        for (JLabel b : botoes) {
            b.setIcon(null); // remove o ícone
            b.setName("" + (n++)); // define o nome
            b.setText(""); // limpa o texto
            b.setEnabled(true); // habilita o botão

            // cor de fundo 
            if (i % 2 == p) { // alterna a cor de fundo
                b.setBackground(CASA_CLARA); // verde claro
            } else {
                b.setBackground(CASA_ESCURA); // verde escuro
            }

            // verifica se mudou de linha 
            if (++i % 8 == 0) { // se é uma nova linha
                if (p == 0) {
                    p = 1; // linha impar
                } else {
                    p = 0; // linha par
                }
            }
        }
    }

    // novo jogo
    private void novo(int pos) {
        itens = new int[64];

        // define as posições das minas
        for (int i = 0; i < qtd_minas; i++) {

            // sorteia uma posição para a mina
            int mina = (int) (Math.random() * 64);

            // ajusta a posição da mina após o clique em 'pos' (evita clicar na mina na primeira jogada)
            if (mina == pos || mina == pos + 1 || mina == pos + 9 || mina == pos - 7 || mina == pos - 8) {
                mina += 2; // move a mina para a direita
            } else if (mina == pos - 1 || mina == pos - 9 || mina == pos + 7 || mina == pos + 8) {
                mina -= 2; // move para a esquerda
            }

            // armazena a posição da mina
            if (mina < 64) {
                itens[mina] = -1;
            }
        }

        // preenche as coordenadas de acordo com a posição de cada mina
        for (int i = 0; i < itens.length; i++) {
            if (itens[i] == -1) { // é uma mina
                // verifica os valores ao redor da mina (borda)
                for (int b : new int[]{i + 1, i + 7, i + 8, i + 9, i - 1, i - 7, i - 8, i - 9}) {
                    if (isBorda(b, i) && itens[b] != -1) { // não é outra mina e é borda do item atual (não está em linhas diferentes)
                        itens[b]++;
                    }
                }
            }
        }

        // debug
//        for (int i = 0; i < itens.length; i++) {
//            if (i % 8 == 0) {
//                System.out.println("");
//            }
//            System.out.print(itens[i] + ",");
//            if (itens[i] == -1) {
//                bandeira(botoes[i]);
//            }
//        }
    }

    // verifica se a casa está desabilitada (se já foi clicada)
    private boolean desabilitado(JLabel b) {
        return b.getBackground().equals(CASA_CLARA_USADA) || b.getBackground().equals(CASA_ESCURA_USADA) || !b.isEnabled();
    }

    // joga ao clicar
    private void jogar(MouseEvent evt) {
        JLabel b = (JLabel) evt.getSource(); // armazena o rótulo clicado

        if (desabilitado(b)) {// desabilitado
            return;
        }

        if (evt.getButton() == 3) { // botão direito

            if (b.getIcon() == null) {
                bandeira(b); // mostra a bandeira
            } else {
                b.setIcon(null); // tira a bandeira
            }

        } else { // botão normal

            if (b.getIcon() != null) { // não funciona se for bandeira
                return;
            }

            // posição clicada
            int pos = Integer.parseInt(b.getName());

            // se é o primeiro clique, gera o novo jogo (evita clicar na bomba na primeira jogada)
            if (novoJogo) {
                novo(pos);
                novoJogo = false;
            }

            // valor da posição
            int v = itens[pos];

            // exibe o valor clicado
            mostrar(pos);

            // se é bomba
            if (v == -1) {
                bloquearTodos();
                JOptionPane.showMessageDialog(rootPane, "Game Over");
                return;
            }
        }

        // verifica se ganhou
        if (ganhou()) {
            bloquearTodos();
            JOptionPane.showMessageDialog(rootPane, "Parabéns!");
        }

    }

    // verifica se o usuário ganhou
    private boolean ganhou() {
        for (int i = 0; i < itens.length; i++) {
            if (botoes[i].getIcon() != null && itens[i] != -1) { // se tem bandeira marcada errado
                return false;
            } else if (botoes[i].getIcon() == null && !desabilitado(botoes[i])) { // se tem botão livre
                return false;
            }
        }
        return true;
    }

    // mostra os valores das casas ao redor da posição clicada 
    private void mostrarBordas(int pos) {
        for (int i : new int[]{pos, pos + 1, pos + 7, pos + 8, pos + 9, pos - 1, pos - 7, pos - 8, pos - 9}) {
            if (i >= 0 && i < 64 && itens[i] != -1 && botoes[i].getText().isEmpty() && isBorda(i, pos)) {
                mostrar(i);
            }
        }
    }

    // mostra o valor da casa selecionada
    private void mostrar(int i) {

        // se o botão já tem bandeira ou está desabilitado
        if (botoes[i].getIcon() != null || desabilitado(botoes[i])) {
            return;
        }

        // altera a cor de fundo da casa
        if (botoes[i].getBackground().equals(CASA_CLARA)) {
            botoes[i].setBackground(CASA_CLARA_USADA);
        } else {
            botoes[i].setBackground(CASA_ESCURA_USADA);
        }

        // se o valor da casa é zero
        if (itens[i] == 0) {
            botoes[i].setText("");
            mostrarBordas(i);
        } else {

            // mostra o valor e altera a cor da letra do item clicado
            botoes[i].setText("" + itens[i]);
            switch (itens[i]) {
                case 1 ->
                    botoes[i].setForeground(COR_NUMERO_UM);
                case 2 ->
                    botoes[i].setForeground(COR_NUMERO_DOIS);
                case 3 ->
                    botoes[i].setForeground(COR_NUMERO_TRES);
                case 4 ->
                    botoes[i].setForeground(COR_NUMERO_QUATRO);
                default ->
                    botoes[i].setForeground(COR_NUMERO_CINCO);
            }
        }

    }

    // bloqueia todos os botões
    private void bloquearTodos() {
        for (int i = 0; i < itens.length; i++) {
            botoes[i].setEnabled(false);
            if (itens[i] == -1) { // mostra as bandeiras não encontradas
                botoes[i].setText("");
                bandeira(botoes[i]);
            }
        }
    }

    // mostra uma bandeira na casa clicada
    private void bandeira(JLabel b) {
        b.setIcon(new ImageIcon(getClass().getResource("/img/flag.png")));
    }

    // verifica se a coordenada 'i' está na borda da posição
    private boolean isBorda(int i, int pos) {

        // dentro do tabuleiro
        if (i >= 0 && i < 64) {

            if (i == pos - 1 && (int) (pos / 8) == (int) (i / 8)) { // esquerda
                return true;
            } else if (i == pos - 7 && (int) (pos / 8) == (int) (i / 8) + 1) { // sup direita
                return true;
            } else if (i == pos - 8 && (int) (pos / 8) == (int) (i / 8) + 1) { // superior
                return true;
            } else if (i == pos - 9 && (int) (pos / 8) == (int) (i / 8) + 1) { // sup esquerda
                return true;
            } else if (i == pos + 1 && (int) (pos / 8) == (int) (i / 8)) { // direita
                return true;
            } else if (i == pos + 7 && (int) (pos / 8) == (int) (i / 8) - 1) { // inf esq
                return true;
            } else if (i == pos + 8 && (int) (pos / 8) == (int) (i / 8) - 1) { // inferior
                return true;
            } else if (i == pos + 9 && (int) (pos / 8) == (int) (i / 8) - 1) { // inf direita
                return true;
            }

        }
        return false;
    }
}
