/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prova;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class Prova extends javax.swing.JFrame {

    private int img1;
    private int img2;
    private int img3;
    private int btn1;
    private int btn2;
    private int btn3;
    private int Vitorias = 0;
    private int Derrotas = 0;
    private String Correto;
    private JButton[] botoes;
    private JLabel[] imagens;

    /**
     * Creates new form Prova
     */
    public Prova() {
        initComponents();
        botoes = new JButton[]{btnOpcao1, btnOpcao2, btnOpcao3, btnNenhum};
        imagens = new JLabel[]{lblImg1, lblImg2, lblImg3};
        iniciarImagens();
        mudarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        btnOpcao1 = new javax.swing.JButton();
        btnOpcao2 = new javax.swing.JButton();
        btnOpcao3 = new javax.swing.JButton();
        btnNenhum = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnIniciarJogo = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tem / Não tem");

        jLabel1.setText("Acertos:");

        lblAcertos.setFont(new java.awt.Font("Segoe UI", 0, 68)); // NOI18N
        lblAcertos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAcertos.setText("0");

        jLabel3.setText("Erros:");

        lblErros.setFont(new java.awt.Font("Segoe UI", 0, 68)); // NOI18N
        lblErros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErros.setText("0");

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barco.png"))); // NOI18N
        lblImg1.setToolTipText("");
        lblImg1.setEnabled(false);

        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barco.png"))); // NOI18N
        lblImg2.setToolTipText("");

        lblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barco.png"))); // NOI18N
        lblImg3.setToolTipText("");
        lblImg3.setEnabled(false);

        btnOpcao1.setText("jButton1");
        btnOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao1ActionPerformed(evt);
            }
        });

        btnOpcao2.setText("jButton1");
        btnOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao2ActionPerformed(evt);
            }
        });

        btnOpcao3.setText("jButton1");
        btnOpcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao3ActionPerformed(evt);
            }
        });

        btnNenhum.setText("Não Tem");
        btnNenhum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNenhumActionPerformed(evt);
            }
        });

        lblResultado.setText("Escolha sua Resposta.");

        jMenu3.setText("Jogo");

        btnIniciarJogo.setSelected(true);
        btnIniciarJogo.setText("Novo jogo");
        btnIniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJogoActionPerformed(evt);
            }
        });
        jMenu3.add(btnIniciarJogo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResultado)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(lblAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addComponent(lblErros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblImg1)
                                    .addGap(58, 58, 58)
                                    .addComponent(lblImg2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblImg3)
                                .addComponent(btnNenhum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg1)
                    .addComponent(lblImg2)
                    .addComponent(lblImg3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpcao1)
                    .addComponent(btnOpcao2)
                    .addComponent(btnOpcao3)
                    .addComponent(btnNenhum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJogoActionPerformed
        iniciarImagens();
        mudarBotoes();
    }//GEN-LAST:event_btnIniciarJogoActionPerformed

    private void btnOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao1ActionPerformed
        jogar(0);
    }//GEN-LAST:event_btnOpcao1ActionPerformed

    private void btnOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao2ActionPerformed
        jogar(1);
    }//GEN-LAST:event_btnOpcao2ActionPerformed

    private void btnOpcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao3ActionPerformed
        jogar(2);
    }//GEN-LAST:event_btnOpcao3ActionPerformed

    private void btnNenhumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNenhumActionPerformed
        naoTem();
    }//GEN-LAST:event_btnNenhumActionPerformed

    private void iniciarImagens() {
        img1 = (int) ((Math.random() * 5) + 1);
        img2 = (int) ((Math.random() * 5) + 1);
        img3 = (int) ((Math.random() * 5) + 1);

        while (img1 == img2 || img2 == img3 || img1 == img3) {
            img1 = (int) ((Math.random() * 5) + 1);
            img2 = (int) ((Math.random() * 5) + 1);
            img3 = (int) ((Math.random() * 5) + 1);
        }

        if (img1 == 1) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
        }
        if (img1 == 2) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
        }
        if (img1 == 3) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
        }
        if (img1 == 4) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
        }
        if (img1 == 5) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
        }

        if (img2 == 1) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
            Correto = "Barco";
        }
        if (img2 == 2) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
            Correto = "Bicicleta";
        }
        if (img2 == 3) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
            Correto = "Carro";
        }
        if (img2 == 4) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
            Correto = "Foguete";
        }
        if (img2 == 5) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
            Correto = "Moto";
        }

        if (img3 == 1) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
        }
        if (img3 == 2) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
        }
        if (img3 == 3) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
        }
        if (img3 == 4) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
        }
        if (img3 == 5) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
        }
    }

    private void mudarBotoes() {

        btn1 = (int) ((Math.random() * 5) + 1);
        btn2 = (int) ((Math.random() * 5) + 1);
        btn3 = (int) ((Math.random() * 5) + 1);

        while (btn1 == btn2 || btn2 == btn3 || btn1 == btn3) {
            btn1 = (int) ((Math.random() * 5) + 1);
            btn2 = (int) ((Math.random() * 5) + 1);
            btn3 = (int) ((Math.random() * 5) + 1);
        }

        if (btn1 == 1) {
            btnOpcao1.setText("Barco");
        }
        if (btn1 == 2) {
            btnOpcao1.setText("Bicicleta");
        }
        if (btn1 == 3) {
            btnOpcao1.setText("Carro");
        }
        if (btn1 == 4) {
            btnOpcao1.setText("Foguete");
        }
        if (btn1 == 5) {
            btnOpcao1.setText("Moto");
        }

        if (btn2 == 1) {
            btnOpcao2.setText("Barco");
        }
        if (btn2 == 2) {
            btnOpcao2.setText("Bicicleta");
        }
        if (btn2 == 3) {
            btnOpcao2.setText("Carro");
        }
        if (btn2 == 4) {
            btnOpcao2.setText("Foguete");
        }
        if (btn2 == 5) {
            btnOpcao2.setText("Moto");
        }

        if (btn3 == 1) {
            btnOpcao3.setText("Barco");
        }
        if (btn3 == 2) {
            btnOpcao3.setText("Bicicleta");
        }
        if (btn3 == 3) {
            btnOpcao3.setText("Carro");
        }
        if (btn3 == 4) {
            btnOpcao3.setText("Foguete");
        }
        if (btn3 == 5) {
            btnOpcao3.setText("Moto");
        }
    }

    private void proximaJogada() {
        img1 = img2;
        img2 = img3;
        img3 = (int) ((Math.random() * 5) + 1);

        while (img3 == img2 || img1 == img3) {
            img3 = (int) ((Math.random() * 5) + 1);
        }

        if (img1 == 1) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
        }
        if (img1 == 2) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
        }
        if (img1 == 3) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
        }
        if (img1 == 4) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
        }
        if (img1 == 5) {
            lblImg1.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
        }

        if (img2 == 1) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
            Correto = "Barco";
        }
        if (img2 == 2) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
            Correto = "Bicicleta";
        }
        if (img2 == 3) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
            Correto = "Carro";
        }
        if (img2 == 4) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
            Correto = "Foguete";
        }
        if (img2 == 5) {
            lblImg2.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
            Correto = "Moto";
        }

        if (img3 == 1) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Barco.png")));
        }
        if (img3 == 2) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Bicicleta.png")));
        }
        if (img3 == 3) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Carro.png")));
        }
        if (img3 == 4) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Foguete.png")));
        }
        if (img3 == 5) {
            lblImg3.setIcon(new ImageIcon(getClass().getResource("/img/Moto.png")));
        }
        mudarBotoes();
    }

    private void jogar(int x) {
        if (botoes[x].getText().equals(Correto)) {
            Vitorias++;
            lblAcertos.setText("" + Vitorias);

            lblResultado.setText("Correto! Você ganhou um ponto.");
            JOptionPane.showMessageDialog(rootPane, "Correto! Você ganhou um ponto.");
            proximaJogada();
        } else {
            Derrotas++;
            lblErros.setText("" + Derrotas);

            lblResultado.setText("Errou, o correto seria " + Correto);
            JOptionPane.showMessageDialog(rootPane, "Errou, o correto seria " + Correto);
            proximaJogada();
        }
    }

    private void naoTem() {
        int validar = 0;

        for (int i = 0; i <= 2; i++) {
            if (botoes[i].getText().equals(Correto)) {
                validar++;
            }
        }

        if (validar > 0) {
            Derrotas++;
            lblErros.setText("" + Derrotas);

            lblResultado.setText("Errou, o correto seria " + Correto);
            JOptionPane.showMessageDialog(rootPane, "Errou, o correto seria " + Correto);

            proximaJogada();
        } else {
            Vitorias++;
            lblAcertos.setText("" + Vitorias);

            lblResultado.setText("Correto! Você ganhou um ponto.");
            JOptionPane.showMessageDialog(rootPane, "Correto! Você ganhou um ponto.");
            proximaJogada();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prova().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem btnIniciarJogo;
    private javax.swing.JButton btnNenhum;
    private javax.swing.JButton btnOpcao1;
    private javax.swing.JButton btnOpcao2;
    private javax.swing.JButton btnOpcao3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
