/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a06ex01;

import javax.swing.ImageIcon;

/**
 *
 * @author ALUNO
 */
public class A06ex01 extends javax.swing.JFrame {

    private int Ale = 0;
    private int euPontos = 0;
    private int pcPontos = 0;
    private int Ganhador = 0;
    
    /**
     * Creates new form A06ex01
     */
    public A06ex01() {
        initComponents();
        btnJogo.setVisible(false);
        btnRecomecar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPcPontos = new javax.swing.JLabel();
        lblTesouraPc = new javax.swing.JLabel();
        lblPapelPc = new javax.swing.JLabel();
        lblPedraPc = new javax.swing.JLabel();
        lblEuPontos = new javax.swing.JLabel();
        lblTesoura = new javax.swing.JLabel();
        lblPapel = new javax.swing.JLabel();
        lblPedra = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        btnJogo = new javax.swing.JButton();
        btnRecomecar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedra Papel ou Tesoura");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblPcPontos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblPcPontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPcPontos.setText("000");
        lblPcPontos.setEnabled(false);

        lblTesouraPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tesoura.png"))); // NOI18N
        lblTesouraPc.setEnabled(false);

        lblPapelPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        lblPapelPc.setEnabled(false);

        lblPedraPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedra.png"))); // NOI18N
        lblPedraPc.setEnabled(false);

        lblEuPontos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblEuPontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEuPontos.setText("000");

        lblTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tesoura.png"))); // NOI18N
        lblTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTesouraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTesouraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTesouraMouseExited(evt);
            }
        });

        lblPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        lblPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPapelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPapelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPapelMouseExited(evt);
            }
        });

        lblPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedra.png"))); // NOI18N
        lblPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPedraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedraMouseExited(evt);
            }
        });

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("X");
        lblTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnJogo.setText("Novo Jogo");
        btnJogo.setToolTipText("");
        btnJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogoActionPerformed(evt);
            }
        });

        btnRecomecar.setText("Recomeçar");
        btnRecomecar.setToolTipText("");
        btnRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomecarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEuPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPcPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPedraPc)
                                .addGap(18, 18, 18)
                                .addComponent(lblPapelPc)
                                .addGap(18, 18, 18)
                                .addComponent(lblTesouraPc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPedra)
                                .addGap(18, 18, 18)
                                .addComponent(lblPapel)
                                .addGap(18, 18, 18)
                                .addComponent(lblTesoura))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnJogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecomecar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPcPontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTesouraPc)
                    .addComponent(lblPapelPc)
                    .addComponent(lblPedraPc))
                .addGap(71, 71, 71)
                .addComponent(lblTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJogo)
                    .addComponent(btnRecomecar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTesoura)
                    .addComponent(lblPapel)
                    .addComponent(lblPedra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEuPontos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int Pc()
    {
        Ale = (int) ((Math.random() * 3) + 1);
        
        if(Ale == 1)
        {  
            lblPedraPc.setEnabled(true);
        }
        else if(Ale == 2)
        {
            lblPapelPc.setEnabled(true);
        }
        else
        {
            lblTesouraPc.setEnabled(true);
        }
        return Ale;
    }
    
    private void Ganhar(int eu)
    {
        if(eu == 1)
        {
            lblPedra.setIcon(new ImageIcon(getClass().getResource("/img/pedra_win.gif")));
        }
        else if(eu == 2)
        {
            lblPapel.setIcon(new ImageIcon(getClass().getResource("/img/papel_win.gif")));
        }
        else
        {
            lblTesoura.setIcon(new ImageIcon(getClass().getResource("/img/tesoura_win.gif")));
        }    
        Ganhador++;
        btnJogo.setVisible(true);
        btnRecomecar.setVisible(true);
    }
    
    private void Jogar(int eu)
    {
        Ale = Pc();
        
        if((Ale == 1 && eu == 2) || (Ale == 2 && eu == 3) || (Ale == 3 && eu == 1))
        {
            Ganhar(eu);
            euPontos++;
            lblEuPontos.setText("" + euPontos);
            lblTexto.setText("Você Ganhou!");
        }
        else if((Ale == 1 && eu == 3) || (Ale == 2 && eu == 1) || (Ale == 3 && eu == 2))
        {
            pcPontos++;
            lblPcPontos.setText("" + pcPontos);
            lblTexto.setText("Você Perdeu!");
            Ganhador++;
            btnJogo.setVisible(true);
            btnRecomecar.setVisible(true);
        }
        else
        {
            lblTexto.setText("Empatou!");
            Ganhador++;
            btnJogo.setVisible(true);
            btnRecomecar.setVisible(true);
        }
    }
    
    private void lblPedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseEntered
        if(Ganhador == 0)
        lblPedra.setIcon(new ImageIcon(getClass().getResource("/img/pedra_azul.png")));
    }//GEN-LAST:event_lblPedraMouseEntered

    private void lblPedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseExited
        if(Ganhador == 0)
        lblPedra.setIcon(new ImageIcon(getClass().getResource("/img/pedra.png")));
    }//GEN-LAST:event_lblPedraMouseExited

    private void lblPapelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseEntered
        if(Ganhador == 0)
        lblPapel.setIcon(new ImageIcon(getClass().getResource("/img/papel_azul.png")));
    }//GEN-LAST:event_lblPapelMouseEntered

    private void lblPapelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseExited
        if(Ganhador == 0)
        lblPapel.setIcon(new ImageIcon(getClass().getResource("/img/papel.png")));
    }//GEN-LAST:event_lblPapelMouseExited

    private void lblTesouraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseEntered
        if(Ganhador == 0)
        lblTesoura.setIcon(new ImageIcon(getClass().getResource("/img/tesoura_azul.png")));
    }//GEN-LAST:event_lblTesouraMouseEntered

    private void lblTesouraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseExited
        if(Ganhador == 0)
        lblTesoura.setIcon(new ImageIcon(getClass().getResource("/img/tesoura.png")));
    }//GEN-LAST:event_lblTesouraMouseExited

    private void lblPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseClicked
        if(Ganhador == 0)
        Jogar(1);
    }//GEN-LAST:event_lblPedraMouseClicked

    private void lblPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseClicked
        if(Ganhador == 0)
        Jogar(2);
    }//GEN-LAST:event_lblPapelMouseClicked

    private void lblTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseClicked
        if(Ganhador == 0)
        Jogar(3);
    }//GEN-LAST:event_lblTesouraMouseClicked

    private void btnRecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomecarActionPerformed
        euPontos = 0;
        pcPontos = 0;
        Ale = 0;
        Ganhador = 0;
        btnJogo.setVisible(false);
        btnRecomecar.setVisible(false);
        lblPedra.setIcon(new ImageIcon(getClass().getResource("/img/pedra.png")));
        lblPapel.setIcon(new ImageIcon(getClass().getResource("/img/papel.png")));
        lblTesoura.setIcon(new ImageIcon(getClass().getResource("/img/tesoura.png")));
        lblPedraPc.setEnabled(false);
        lblPapelPc.setEnabled(false);
        lblTesouraPc.setEnabled(false);
        lblPcPontos.setText("000");
        lblEuPontos.setText("000");
        lblTexto.setText("X");
    }//GEN-LAST:event_btnRecomecarActionPerformed

    private void btnJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogoActionPerformed
        Ganhador = 0;
        Ale = 0;
        btnJogo.setVisible(false);
        btnRecomecar.setVisible(false);
        lblPedra.setIcon(new ImageIcon(getClass().getResource("/img/pedra.png")));
        lblPapel.setIcon(new ImageIcon(getClass().getResource("/img/papel.png")));
        lblTesoura.setIcon(new ImageIcon(getClass().getResource("/img/tesoura.png")));
        lblPedraPc.setEnabled(false);
        lblPapelPc.setEnabled(false);
        lblTesouraPc.setEnabled(false);
        lblTexto.setText("X");
    }//GEN-LAST:event_btnJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A06ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A06ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A06ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A06ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A06ex01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogo;
    private javax.swing.JButton btnRecomecar;
    private javax.swing.JLabel lblEuPontos;
    private javax.swing.JLabel lblPapel;
    private javax.swing.JLabel lblPapelPc;
    private javax.swing.JLabel lblPcPontos;
    private javax.swing.JLabel lblPedra;
    private javax.swing.JLabel lblPedraPc;
    private javax.swing.JLabel lblTesoura;
    private javax.swing.JLabel lblTesouraPc;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
